### ISSUE TITLE
openshift_auth fails when host has a trailing slash.

### ISSUE THREAD

**Issue by paulczar** [openshift/community.okd#139]
This happens on ARO (Azure Red Hat OpenShift), I would assume the same behavior happens in other OCP 4.x clusters.

I believe the issue here is we [hardcode](https://github.com/openshift/community.okd/blob/main/plugins/modules/openshift_auth.py#L269) in a `/` vs using `urllib.parse.urljoin` or `file.path.join` to deal with reduntant slashes. 

The following ansible

```yaml
- name: check cluster
  azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_aro_cluster }}"
  register: _aro_cluster

- name: get credentials
  azure_rm_openshiftmanagedcluster_credentials_info:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_aro_cluster }}"
  register: _aro_creds

- debug:
    var: _aro_cluster

- set_fact:
    kube_api: "{{ _aro_cluster.clusters.properties.apiserverProfile.url }}"
    ocp_console: "{{ _aro_cluster.clusters.properties.consoleProfile.url }}"
    kube_username: "{{ _aro_creds.credentials.kubeadminUsername }}"
    kube_password: "{{ _aro_creds.credentials.kubeadminPassword }}"
  # no_log: true

- name: get access token from openshift
  community.okd.openshift_auth:
    host: "{{ kube_api }}"
    username: "{{ kube_username }}"
    password: "{{ kube_password }}"
  register: openshift_auth_results
```

results in

```
fatal: [localhost]: FAILED! => changed=false
  msg: Couldn't find OpenShift's OAuth API
  req_method: GET
  req_reason: Forbidden
  req_status_code: 403
  req_url: https://api.xxxxx.eastus.aroapp.io:6443//.well-known/oauth-authorization-server
```
