### ISSUE TITLE
Unable to connect to a pod using the inventory plugin.

### ISSUE THREAD

**Issue by piyengar** [openshift/community.okd#144]
I am trying to backup a postgres DB running on openshift. I have an inventory file using the `community.okd.openshift` plugin and am able to list all the hosts in my namespace using this config. 

```
@all:
  |--@xxx.xxx.xxx_6443:
  |  |--@namespace_ansible-db-test:
  |  |  |--@namespace_ansible-db-test_pods:
  |  |  |  |--postgresql-1-deploy_deployment
  |  |  |  |--postgresql-1-zvk9k_postgresql
  |  |  |--@namespace_ansible-db-test_routes:
  |  |  |--@namespace_ansible-db-test_services:
  |  |  |  |--postgresql
  |--@label_deployment_postgresql-1:
  |  |--postgresql-1-zvk9k_postgresql
  |--@label_deploymentconfig_postgresql:
  |  |--postgresql-1-zvk9k_postgresql
  |--@label_name_postgresql:
  |  |--postgresql-1-zvk9k_postgresql
  |--@label_openshift.io/deployer-pod-for.name_postgresql-1:
  |  |--postgresql-1-deploy_deployment
  |--@label_template.openshift.io/template-instance-owner_ffc16a7a-5243-48a4-993a-5b61e3e8ea92:
  |  |--postgresql
  |--@label_template_postgresql-ephemeral-template:
  |  |--postgresql
  |--@ungrouped:
```

But when I try to ping the pod or even run a debug message, the run fails in the gather_facts step. This is the message that I get.

```
<postgresql-1-zvk9k_postgresql> ESTABLISH oc CONNECTION
<postgresql-1-zvk9k_postgresql> EXEC ['/usr/local/bin/oc', '-n', 'ansible-db-test', 'exec', '-i', 'postgresql-1-zvk9k', '-c', 'postgresql', '--', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /tmp/ `"&& mkdir "` echo /tmp/ansible-tmp-1649114380.5317209-68473-280544582421228 `" && echo ansible-tmp-1649114380.5317209-68473-280544582421228="` echo /tmp/ansible-tmp-1649114380.5317209-68473-280544582421228 `" ) && sleep 0\'']
fatal: [postgresql-1-zvk9k_postgresql]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ `\"&& mkdir \"` echo /tmp/ansible-tmp-1649114380.5317209-68473-280544582421228 `\" && echo ansible-tmp-1649114380.5317209-68473-280544582421228=\"` echo /tmp/ansible-tmp-1649114380.5317209-68473-280544582421228 `\" ), exited with result 1",
    "unreachable": true
}
```

This is my inventory file
```yml
plugin: community.okd.openshift
connections:
  - host: <REDACTED>
    api_key: "<REDACTED>"
    verify_ssl: false
    namespaces:
      - ansible-db-test
```
And this is my playbook
```yml
---
- name: Backup Databases
  hosts: namespace_ansible-db-test:&label_name_postgresql
  tasks:
  - name: debug message on consul-0 pod
    debug:
      var: hostvars[inventory_hostname]

  - shell: hostname
```

Ansible configuration
```
pi$ ansible --version
ansible 2.10.17
  config file = None
  configured module search path = ['/Users/pi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pi/.pyenv/versions/miniconda3-latest/envs/rnoc/lib/python3.9/site-packages/ansible
  executable location = /Users/pi/.pyenv/versions/miniconda3-latest/envs/rnoc/bin/ansible
  python version = 3.9.5 (default, May 18 2021, 12:31:01) [Clang 10.0.0 ]
```

The strange thing is that when I run the playbook after I login using `oc login`, it runs perfectly fine. 

Am I missing something here? I thought that the connection encapsulates the login flow as well and we should be able to use the host as is.
