### ISSUE TITLE
discard api_key/token after mark it absent 

### ISSUE THREAD

**Issue by ankujuniyal** [openshift/community.okd#176]
My question is When we say state abest of api_key on module community.okd.openshift_auth , So it should mark remove/invalid  token  from K8. 
As last token still can be used until K8 mark it invalid. 

ansible-playbook --version
ansible-playbook [core 2.13.5]

OKD, Kubernetes version -   v1.21.2-1505+6438632813d726-dirty

```
- hosts: localhost
  module_defaults:
    group/community.okd.okd:
      host: https://api.okdstgn.example.com:443
      validate_certs: false

  tasks:
  - block:
    # It's good practice to store login credentials in a secure vault and not
    # directly in playbooks.
    # - include_vars: k8s_passwords.yml

    - name: Log in (obtain access token)
      community.okd.openshift_auth:
        # host: https://api.okdstgn.example.com:443
        username: admin
        password: admin
        validate_certs: false
      register: openshift_auth_results

#Working 
    # - name: Get a list of all pods from any namespace
    #   kubernetes.core.k8s_info:
    #     api_key: "{{ openshift_auth_results.openshift_auth.api_key  }}"
    #     kind: Pod
    #     validate_certs: false
    #   register: pod_list

#TODO Need to look why still token can be used even after mark as absent
    always:
    - name: If login succeeded, try to log out (revoke access token)
      when: openshift_auth_results.openshift_auth.api_key is defined
      community.okd.openshift_auth:
        state: absent
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"      
        # host: https://api.okdstgn.example.com:443
        # validate_certs: false
```

reference:- 
[k8s_auth ](https://docs.ansible.com/ansible/3/collections/community/kubernetes/k8s_auth_module.html) 
[okd-openshift-auth](https://docs.ansible.com/ansible/latest/collections/community/okd/openshift_auth_module.html#ansible-collections-community-okd-openshift-auth-module)
