### ISSUE TITLE
openshift_route - Route specific Annotations

### ISSUE THREAD

**Issue by abkura** [openshift/community.okd#75]
##### SUMMARY
How to pass Route specific annotations while creating route on OCP. 

Example:

haproxy.router.openshift.io/balance : source 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
openshift_route

##### ANSIBLE VERSION

```paste below

```

**Comment by abikouo** [comment]
@abkura thanks for taking the time to report this issue.
The ``openshit_route`` module does not support Route annotations for the time being, but the module has been improved in PR #99 you can use it to test. 
However if you want to continue working with current community.okd release version you can using the ``community.okd.k8s`` module to create the route with annotations like this:

```
- name: create openshift route using k8s module
  community.okd.k8s:
    name: test
    namespace: default
    definition:
        kind: Route
        api_version: route.openshift.io/v1
        metadata:
            annotations:
                haproxy.router.openshift.io/balance: round-robin
        (...)
```
